Enhance the support for reading Results and Records across multiple collections
tektoncd/results pull request #249
Opened 2022-10-07 15:37 UTC by alan-ghelardi

## What

This pull request resolves https://github.com/tektoncd/results/issues/248, which
provides a more detailed explanation about the rationale. Essentially, these
changes allow users to list results across parents and list records across
results without a prior knowledge of the parent name.

2022-10-07 17:22 UTC, dibyom commented
/ok-to-test

2022-10-07 17:47 UTC, adambkaplan requested changes
If we are going to use `-` to mean "all namespaces" for the parent, then we need to modify the RBAC auth check [1]. `-` is not a valid namespace, and the best case is that subject access review will fail with an invalid namespace. Worst case - it always succeeds, which would be a security vulnerability.

Ideally we would have an e2e test covering this. I feel that is too much to ask for in this PR.

[1] https://github.com/tektoncd/results/blob/main/pkg/api/server/v1alpha2/auth/rbac.go#L85-L94

2022-10-10 14:29 UTC, adambkaplan approved these changes
/approve

2022-10-10 14:39 UTC, vdemeester approved these changes
/lgtm

2022-10-10 14:41 UTC, merged

2022-10-10 20:49 UTC, alan-ghelardi commented
@adambkaplan  thank you for accepting the pull request. I started writing an E2E test case for that scenario, but I stumbled upon the mtls. I'm working on that and I send a new pull request once it's done.

2023-02-27 11:52 UTC, khrm reviewed
/kind feature
We need this label for release as discussed in the last WG call.